version: "3.4"

volumes:
  azurite: {}
  ideamachine_sql: {}
  seq: {}

networks:
  ideamachinenetwork: {}

services:
  nginx.ingress:
    image: nginx
    container_name: ideamachine.nginx
    labels:
      - ideamachinecompose
    networks:
      - ideamachinenetwork
    ports:
      - 1253:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./Scripts/Docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./Scripts/Docker/nginx/cert:/etc/nginx/cert

  ideamachineweb:
    image: ${DOCKER_REGISTRY-}ideamachineweb
    container_name: ideamachineweb
    labels:
      - ideamachinecompose
    networks:
      - ideamachinenetwork
    build:
      context: .
      dockerfile: Services/IdeaMachineWeb/Dockerfile
    environment:
      ASPNETCORE_URLS: "http://+:80"
      DbConnectionString: "Server=tcp:ideamachine.sql,1433;User ID=SA;Password=^dEbX2Ew;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;"
      RabbitMqSettings__BrokerAddress: ideamachine.rabbitmq
      RabbitMqSettings__UserName: ideamachine
      RabbitMqSettings__Password: ideamachine
      BlobStorageConnection: AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;DefaultEndpointsProtocol=https;BlobEndpoint=https://ideamachine.azurite:10000/devstoreaccount1;QueueEndpoint=https://ideamachine.azurite:10001/devstoreaccount1;TableEndpoint=https://ideamachine.azurite:10002/devstoreaccount1
      GmailUserName: "ideamachinenews@gmail.com"
      Seq_Server: "http://ideamachine.seq:5341"
      DeploymentLink: "https://localhost:1253/"
    volumes:
      - /Keys/Storage:/keys/storage
    depends_on:
      - ideamachine.sql
      - ideamachine.rabbitmq

  ideamachine.accountservice:
    image: ${DOCKER_REGISTRY-}ideamachineaccountservice
    container_name: ideamachine.accountservice
    labels:
      - ideamachinecompose
    networks:
      - ideamachinenetwork
    build:
      context: .
      dockerfile: Services/IdeaMachine.AccountService/Dockerfile
    environment:
      ASPNETCORE_URLS: "http://+:80"
      DbConnectionString: "Server=tcp:ideamachine.sql,1433;User ID=SA;Password=^dEbX2Ew;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;"
      RabbitMqSettings__BrokerAddress: ideamachine.rabbitmq
      RabbitMqSettings__UserName: ideamachine
      RabbitMqSettings__Password: ideamachine
      IdeaMachine_RabbitMq: ideamachine.rabbitmq
      Seq_Server: "http://ideamachine.seq:5341"
    volumes:
      - /Keys/Storage:/keys/storage
    depends_on:
      - ideamachine.sql
      - ideamachine.rabbitmq

  ideamachine.sql:
    image: ideamachinesql
    container_name: ideamachine.sql
    build:
      context: Scripts/Docker/mssql
      dockerfile: ./Dockerfile
    labels:
      - ideamachinecompose
    networks:
      - ideamachinenetwork
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "^dEbX2Ew"
    volumes:
      - ideamachine_sql:/var/opt/mssql
      - ./Scripts/Docker/mssql:/scripts
    restart: unless-stopped

  ideamachine.seq:
    image: datalust/seq:latest
    container_name: ideamachine.seq
    labels:
      - ideamachinecompose
    networks:
      - ideamachinenetwork
    ports:
      - "5341:80"
    environment:
      ACCEPT_EULA: "Y"
    volumes:
      - seq:/data

  ideamachine.rabbitmq:
    image: ideamachinerabbitmq
    container_name: ideamachine.rabbitmq
    labels:
      - ideamachinecompose
    build:
      context: Scripts/Docker/rabbitmq
      dockerfile: Dockerfile
    networks:
      - ideamachinenetwork
    ports:
      - "15672:15672"

  ideamachine.azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.14.0
    container_name: ideamachine.azurite
    networks:
      - ideamachinenetwork
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    entrypoint: "azurite --loose -l /data --oauth=basic --cert=/azuriteDir/azuriteCert.crt --key=/azuriteDir/azuriteKey.pem --blobPort 10000 --blobHost 0.0.0.0 --queuePort 10001 --queueHost 0.0.0.0 --tablePort 10002 --tableHost 0.0.0.0"
    labels:
      - ideamachinecompose
    volumes:
      - azurite:/data
      - ./AzuriteCert:/azuriteDir

  ideamachine.profilepictureservice:
    image: ${DOCKER_REGISTRY-}ideamachineprofilepictureservice
    container_name: ideamachine.functions.profilepictureservice
    labels:
      - ideamachinecompose
    networks:
      - ideamachinenetwork
    build:
      context: .
      dockerfile: Services/IdeaMachine.ProfilePictureService/Dockerfile
    environment:
      RabbitMqSettings__BrokerAddress: ideamachine.rabbitmq
      RabbitMqSettings__UserName: ideamachine
      RabbitMqSettings__Password: ideamachine
    depends_on:
      - ideamachine.sql
      - ideamachine.rabbitmq