version: '3.4'

volumes:
  ideamachine_postgres: {}

services:
  ideamachine:
    image: ${DOCKER_REGISTRY-}ideamachine
    build:
      context: .
      dockerfile: IdeaMachine/Dockerfile
    ports:
      - "1456:80"
      - "1457:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PostgresConnectionString=Server=ideamachine.postgres;Port=5432;User Id=ideamachine;Password=ideamachine;Database=ideamachine;
      - IdeaMachine_RabbitMq=ideamachine.rabbitmq
      - GmailUserName=ideamachinenews@gmail.com
      - GmailPassword=LwtqQp6bBUVE7j2IhmVT
    depends_on:
      - ideamachine.postgres
      - ideamachine.rabbitmq

  ideamachine.postgres:
    container_name: ideamachine.postgres
    image: postgres
    labels:
      - ideamachinecompose
    ports:
      - "5432:5432"
      - "8080:8080"
    environment:
      - POSTGRES_USER=ideamachine
      - POSTGRES_PASSWORD=ideamachine
    volumes:
      - ideamachine_postgres:/var/lib/postgresql/data
      - ./Module/IdeaMachine.Module.Idea/Repository/Scripts/Idea.sql:/docker-entrypoint-initdb.d/Idea.sql

  ideamachine.rabbitmq:
    image: docker.io/library/rabbitmq:3.8.6-management
    labels:
      - ideamachinecompose
    ports:
      - "15672:15672"