version: '3.4'

services:
  ideamachineweb:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  ideamachine.accountservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
