version: '3.4'

volumes:
  ideamachine_sql: {}
  seq: {}

services:
  ideamachine:
    image: ${DOCKER_REGISTRY-}ideamachine
    labels:
      - ideamachinecompose
    build:
      context: .
      dockerfile: IdeaMachine/Dockerfile
    ports:
      - "1456:80"
      - "1457:443"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DbConnectionString: "Server=tcp:ideamachine.sql,1433;User ID=SA;Password=^dEbX2Ew;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;"
      IdeaMachine_RabbitMq: "ideamachine.rabbitmq"
      BlobStorageConnection: "DefaultEndpointsProtocol=https;AccountName=ideamachine;AccountKey=UACIUfu/dASKQJSwvwYpvsn74usor69WgNCzP7xlxIumycC1LFyWYptQ1xBcnw8jBsoBI3tD5ysemzdmMMiH6g==;EndpointSuffix=core.windows.net"
      GmailUserName: "ideamachinenews@gmail.com"
      GmailServiceAccountKey: -----BEGIN PRIVATE KEY-----MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCpfCC47cMRCXBcUKzPL3wOkiU1XEmuxkc7mbVG1E5WongKsekfnvzXInA4AkFqYeX3Zbxkdyq93Qqh2wWHCkXxP93bn12LV2/INQifxL5vODYOgzhvrPVUs4VNCEijBBqtYMFMf1jrgPl+bI0CC1z9oQqPEnTzSDB+km4qHZklGsxtOTYKYjP+Dzsccsg05LNCKNTEMwGHJB3dsEHS6x1fJlQesLkOVcGDE86JYqDWhmHLKjsSUmZtJhfQrZQ3XX+DfqOx919ghe0uj9jqVwAo86NwbJi3fNuYsHdLnx7lQHqoaQWoJjwUwk++/FVUxcfIQnga+HHzoR3H2XOyK2QNAgMBAAECggEAAnUoqvsqUKKYvNif+OJ7uQuzexebK0FNd8wdzdN2+K34cadCIHxCDFiVKgAWX2rgq9APhaFuFDy9UmWGVKlNzwFvFSfgHQzSiSOuZqqysZLYwyhx9rnvq3UYTL//AFDR64uzTImtihS1CXlHfi0YrHDbt1a8LWmcPRRLK/8r4QGBb19++qJZgehWy4j7A8tmOOna8lueyxSJ2ss9i2F2nooeMkd+yMIUw7t/bcU08pMJFCYg6S8nvqUT5oI/hrOCaskJePKC/svZoYtlCBIbwUmjyG5vxwMKooG/HuE6yM0NgZspD2VnNATcMQfNwdS5sERDGd3yD7GXqP8cyBwyvQKBgQDTWPQFddblV/c/FW0pIvIIAptSkRbIgWWXy0Z2YX5FosJdk7kP/Np4aM+zjnu3U2qQqDO5AGNrTxQ6LB1iXbKTewlSnpv0Wb5TQCNkmLmUcRLb+MSId7y/QZkhGk3xqKx5se7rA5KYrb3b+5ypFXlrvgnsl4Dj4BlXQE6gRLXsZwKBgQDNSvkKSxg+ga3W4xNNJk8muB+6tjwl+ilOIZALkUyyYZc3WzDXbExzzfYIJCAYtmKT2Rjh+X3zW/wrJ+P2VMOsSlV15R4x1ctY55erU418CzB/EzVuaTGdUJz1lg9y6GVofw1dY4gSuM1DNvBL/2pM3fdYkOxlI1ZiQGXNFQSjawKBgE16/OrLip7FovTTjBNaplRdcEfSvQGAvpfpg8l+cGZjBtJ7h4re7dDay9pNz/kjcZvariuSguAiO44gAh2/r+n1XzOUxiPMisPGbbNBcjeDRKC0EIjfLKkJCXRjSlPfvGtY2ff6dVHX0BTHp2UtZDglkUnVOQFRdLjR8IE871zdAoGAFbepstoQ3YPwdPwerZmw4+K0kJb4s/fL6NUKHP8pAvHqAlQmTZPKXrHaJjBUKOkacpOT20v+dAE2IwacShHbhV1zvv4W/KSmV2hgliJHpGi2n6rTizObqQ2/HQfb6IcHO0+9hTSjT3+3TzX/o7qIb0tIAFmMeIKNf+VaH6DqlbMCgYEAuqlj3Rjhj+F5kSdi2UzqD+NkUmmGPCxJq9jwjgnBs7ll4U+pucIJnBCiMIoSmIuT/i0WBAkZdHvTaJjEDyfKHmtJyr13tCl76h6CrZCv4QQSUC1wJe+E/KZxv7BSM1Vyq8u6VLd4nz09ArH/fLHoRhIq9yqIMWC3yCji0JkEzms=-----END PRIVATE KEY-----
      GmailPassword: "LwtqQp6bBUVE7j2IhmVT"
      Seq_Server: "http://ideamachine.seq:5341"
      DeploymentLink: "https://localhost:1457"
    depends_on:
      - ideamachine.sql
      - ideamachine.rabbitmq


  ideamachine.accountservice:
    image: ${DOCKER_REGISTRY-}ideamachineaccountservice
    labels:
      - ideamachinecompose
    build:
      context: .
      dockerfile: Services/IdeaMachine.AccountService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DbConnectionString: "Server=tcp:ideamachine.sql,1433;User ID=SA;Password=^dEbX2Ew;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;"
      IdeaMachine_RabbitMq: "ideamachine.rabbitmq"
      Seq_Server: "http://ideamachine.seq:5341"
    depends_on:
      - ideamachine.sql
      - ideamachine.rabbitmq

  ideamachine.sql:
    image: mcr.microsoft.com/mssql/server
    labels:
      - ideamachinecompose
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "^dEbX2Ew"
    volumes:
        - ideamachine_sql:/var/opt/mssql
        - ./database:/Scripts/dbInit.sql
    restart: unless-stopped

  ideamachine.seq:
    image: datalust/seq:latest
    labels:
      - ideamachinecompose
    ports:
      - "5341:80"
    environment:
      ACCEPT_EULA: "Y"
    volumes:
      - seq:/data

  ideamachine.rabbitmq:
    image: docker.io/library/rabbitmq:3.8.6-management
    labels:
      - ideamachinecompose
    ports:
      - "15672:15672"
