//----------------------
//This file was autogenerated by GrpcProxyGenerator.Service.GrpcProxyFactory
//Timestamp of generation: UTC 14/11/2021 18:42:25
//----------------------

namespace IdeaMachine.Common.RemotingProxies.Proxies
{
	public class AccountServiceProxy : IdeaMachine.Common.RemotingProxies.ProxyInvocation.AbstractDeploymentProxy<IdeaMachine.Modules.Account.Service.Interface.IAccountService>, IdeaMachine.Modules.Account.Service.Interface.IAccountService
	{
		public AccountServiceProxy(IdeaMachine.Common.Grpc.Service.Interface.IGrpcChannelProvider channelProvider)
			: base(channelProvider,
				IdeaMachine.Common.IPC.ServiceType.AccountService)
		{ }

		public System.Threading.Tasks.Task<IdeaMachine.Modules.Account.Abstractions.DataTypes.Model.GetAccountName.Response> GetAccountName(
			IdeaMachine.Modules.Account.Abstractions.DataTypes.Model.GetAccountName.Request getAccountNameModel)
			=> InvokeWithResult(service => service.GetAccountName(
				getAccountNameModel));

	}
}
