//----------------------
//This file was autogenerated by GrpcProxyGenerator.Service.GrpcProxyFactory
//Timestamp of generation: UTC 06/01/2022 20:47:12
//----------------------

namespace IdeaMachine.Common.RemotingProxies.Proxies
{
	public class SocialLoginServiceProxy : IdeaMachine.Common.RemotingProxies.ProxyInvocation.AbstractDeploymentProxy<IdeaMachine.Modules.Account.Service.Interface.ISocialLoginService>, IdeaMachine.Modules.Account.Service.Interface.ISocialLoginService
	{
		public SocialLoginServiceProxy(IdeaMachine.Common.Grpc.Service.Interface.IGrpcChannelProvider channelProvider)
			: base(channelProvider,
				IdeaMachine.Common.IPC.ServiceType.AccountService)
		{ }

		public System.Threading.Tasks.Task<IdeaMachine.Common.Core.Utils.IPC.ServiceResponse> AddExternalUser(
			IdeaMachine.Modules.Account.DataTypes.Model.SocialLoginInformation loginInfo)
			=> InvokeWithResult(service => service.AddExternalUser(
				loginInfo));

	}
}
