apiVersion: v1
kind: Service
metadata:
  name: ideamachine-rabbitmq
spec:
  type: ClusterIP
  selector:
    name: ideamachine-rabbitmq
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ideamachine-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ideamachine-rabbitmq
  template:
    metadata:
      name: ideamachine-rabbitmq
      labels:
        name: ideamachine-rabbitmq
    spec:
      containers:
        - name: ideamachine-rabbitmq
          image: ideamachine.azurecr.io/ideamachinerabbitmq
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 5672
      imagePullSecrets:
        - name: acrimgpullsecret
